
uvmf:
  environments:
    AND:  
      agents:
      - name: AND_inputs_agent  
        type: AND_inputs 
        initiator_responder: "INITIATOR"  
      - name: AND_output_agent  
        type: AND_output 
        initiator_responder: "RESPONDER" 

      analysis_components:
      - name: AND_pred
        type: AND_predictor #component name (it has dedicated yaml file)
      #These allow the user to specify analysis exports & ports to add to the environment class, typically implemented when the block level environment is to be utilized within a larger system level UVM testbench.  
      analysis_exports: []
      analysis_ports: []

      config_constraints: []
      config_vars: []
    
      parameters: []
    
      scoreboards:
      - name: AND_sb
        sb_type: uvmf_in_order_scoreboard
        trans_type: AND_output_transaction
    
      subenvs: []
    
      tlm_connections:  #specify a point to point connection between ports/exports
      - driver: AND_inputs_agent.monitored_ap       # connection 00     
        receiver: AND_pred.AND_inputs_agent_ae                            
      - driver: AND_pred.AND_sb_ap                  # connection 01
        receiver: AND_sb.expected_analysis_export
      - driver: AND_output_agent.monitored_ap       # connection 02
        receiver: AND_sb.actual_analysis_export
