uvmf:
  environments:
    OR:
      agents:
      - name: OR_in_agent
        type: OR_in
        initiator_responder: "INITIATOR"
      - name: OR_out_agent
        type: OR_out
        initiator_responder: "RESPONDER"
      analysis_components:
      - name: OR_pred
        type: OR_predictor
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      parameters: []
      scoreboards:
      - name: OR_sb
        sb_type: uvmf_in_order_scoreboard
        trans_type: OR_out_transaction
      subenvs: []
      tlm_connections:
      - driver: OR_in_agent.monitored_ap
        receiver: OR_pred.OR_in_agent_ae
      - driver: OR_pred.OR_sb_ap
        receiver: OR_sb.expected_analysis_export
      - driver: OR_out_agent.monitored_ap
        receiver: OR_sb.actual_analysis_export
